// Generated by logs/tools/build_word_course.mjs. Edit the reviewed course source, not this file.
const WORD_COURSE = {
  "id": "one-focus-word-course-v1",
  "levels": [
    {
      "level": 1,
      "id": "short-a",
      "phase": "Short vowels",
      "focus": "Short a, as in cat",
      "focusWords": [
        "cat",
        "map",
        "tap",
        "sad",
        "bag",
        "jam"
      ],
      "focusWordIds": [
        "word:cat",
        "word:map",
        "word:tap",
        "word:sad",
        "word:bag",
        "word:jam"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter A.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In cat, this letter makes the middle sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "a"
        },
        {
          "kind": "speech",
          "text": "cat. map."
        }
      ],
      "artwork": "images/l1_lonemarine.jpg",
      "artworkCredit": null
    },
    {
      "level": 2,
      "id": "short-e",
      "phase": "Short vowels",
      "focus": "Short e, as in bed",
      "focusWords": [
        "bed",
        "red",
        "hen",
        "pen",
        "net",
        "wet"
      ],
      "focusWordIds": [
        "word:bed",
        "word:red",
        "word:hen",
        "word:pen",
        "word:net",
        "word:wet"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter E.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In bed, this letter makes the middle sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "e"
        },
        {
          "kind": "speech",
          "text": "bed. red."
        }
      ],
      "artwork": "images/word-course/tank-01-m1-abrams.jpg",
      "artworkCredit": {
        "title": "Completed M1 Abrams Tank Chrysler Lima 1979",
        "author": "Unknown author",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Completed_M1_Abrams_Tank_Chrysler_Lima_1979.jpg",
        "license": "Public domain",
        "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 3,
      "id": "short-i",
      "phase": "Short vowels",
      "focus": "Short i, as in pig",
      "focusWords": [
        "pig",
        "sit",
        "pin",
        "lip",
        "dig",
        "fin"
      ],
      "focusWordIds": [
        "word:pig",
        "word:sit",
        "word:pin",
        "word:lip",
        "word:dig",
        "word:fin"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter I.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In pig, this letter makes the middle sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "i"
        },
        {
          "kind": "speech",
          "text": "pig. sit."
        }
      ],
      "artwork": "images/word-course/tank-02-leopard-2.jpg",
      "artworkCredit": {
        "title": "Leopard 2 A5 der Bundeswehr",
        "author": "Bundeswehr-Fotos",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Leopard_2_A5_der_Bundeswehr.jpg",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 4,
      "id": "short-o",
      "phase": "Short vowels",
      "focus": "Short o, as in dog",
      "focusWords": [
        "dog",
        "log",
        "pot",
        "hot",
        "top",
        "mop"
      ],
      "focusWordIds": [
        "word:dog",
        "word:log",
        "word:pot",
        "word:hot",
        "word:top",
        "word:mop"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In dog, this letter makes the middle sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "o"
        },
        {
          "kind": "speech",
          "text": "dog. log."
        }
      ],
      "artwork": "images/word-course/tank-03-challenger-2.jpg",
      "artworkCredit": {
        "title": "Challenger 2 MBT in Estonia-902250",
        "author": "Andrii Nikolaienko",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Challenger_2_MBT_in_Estonia-902250.jpeg",
        "license": "CC0",
        "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 5,
      "id": "short-u",
      "phase": "Short vowels",
      "focus": "Short u, as in sun",
      "focusWords": [
        "sun",
        "cup",
        "bus",
        "mud",
        "run",
        "hut"
      ],
      "focusWordIds": [
        "word:sun",
        "word:cup",
        "word:bus",
        "word:mud",
        "word:run",
        "word:hut"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter U.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In sun, this letter makes the middle sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "u"
        },
        {
          "kind": "speech",
          "text": "sun. cup."
        }
      ],
      "artwork": "images/l2_cathedralknight.jpg",
      "artworkCredit": null
    },
    {
      "level": 6,
      "id": "initial-blends",
      "phase": "Blending and doubled letters",
      "focus": "Blend known consonant sounds at the start",
      "focusWords": [
        "clap",
        "flag",
        "frog",
        "plum",
        "stop",
        "swim"
      ],
      "focusWordIds": [
        "word:clap",
        "word:flag",
        "word:frog",
        "word:plum",
        "word:stop",
        "word:swim"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "In clap, keep the two starting consonant sounds together. Listen to each sound."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "c"
        },
        {
          "kind": "recorded-sound",
          "clipKey": "l"
        },
        {
          "kind": "speech",
          "text": "clap."
        }
      ],
      "artwork": "images/word-course/tank-04-leclerc.jpg",
      "artworkCredit": {
        "title": "Leclerc-openphotonet PICT6015",
        "author": "Daniel Steger (Lausanne,Switzerland)",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Leclerc-openphotonet_PICT6015.JPG",
        "license": "CC BY-SA 2.5",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 7,
      "id": "final-blends",
      "phase": "Blending and doubled letters",
      "focus": "Blend known consonant sounds at the end",
      "focusWords": [
        "hand",
        "tent",
        "lamp",
        "milk",
        "pond",
        "dust"
      ],
      "focusWordIds": [
        "word:hand",
        "word:tent",
        "word:lamp",
        "word:milk",
        "word:pond",
        "word:dust"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "In hand, keep the two ending consonant sounds together. Listen to each sound."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "n"
        },
        {
          "kind": "recorded-sound",
          "clipKey": "d"
        },
        {
          "kind": "speech",
          "text": "hand."
        }
      ],
      "artwork": "images/word-course/tank-05-merkava.jpg",
      "artworkCredit": {
        "title": "Merkava Mk III tank 01",
        "author": "Staselnik",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Merkava_Mk_III_tank_01.jpg",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 8,
      "id": "ck",
      "phase": "Blending and doubled letters",
      "focus": "ck says k",
      "focusWords": [
        "back",
        "neck",
        "kick",
        "rock",
        "duck",
        "sock"
      ],
      "focusWordIds": [
        "word:back",
        "word:neck",
        "word:kick",
        "word:rock",
        "word:duck",
        "word:sock"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter C.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter K.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make one sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ck"
        },
        {
          "kind": "speech",
          "text": "back. neck."
        }
      ],
      "artwork": "images/word-course/tank-06-k2-black-panther.jpg",
      "artworkCredit": {
        "title": "K2 Tank Joins the Fight with eFP Battle Group Poland - 2",
        "author": "Staff Sgt. Matthew Foster",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:K2_Tank_Joins_the_Fight_with_eFP_Battle_Group_Poland_-_2.jpg",
        "license": "Public domain",
        "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 9,
      "id": "ff",
      "phase": "Blending and doubled letters",
      "focus": "ff says f",
      "focusWords": [
        "off",
        "puff",
        "huff",
        "cuff",
        "sniff",
        "stiff"
      ],
      "focusWordIds": [
        "word:off",
        "word:puff",
        "word:huff",
        "word:cuff",
        "word:sniff",
        "word:stiff"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter F.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter F.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make one sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "f"
        },
        {
          "kind": "speech",
          "text": "off. puff."
        }
      ],
      "artwork": "images/l3_helmet.jpg",
      "artworkCredit": null
    },
    {
      "level": 10,
      "id": "ll",
      "phase": "Blending and doubled letters",
      "focus": "ll says l",
      "focusWords": [
        "bell",
        "hill",
        "doll",
        "tell",
        "well",
        "fill"
      ],
      "focusWordIds": [
        "word:bell",
        "word:hill",
        "word:doll",
        "word:tell",
        "word:well",
        "word:fill"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter L.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter L.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make one sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ll"
        },
        {
          "kind": "speech",
          "text": "bell. hill."
        }
      ],
      "artwork": "images/word-course/tank-07-type-10.jpg",
      "artworkCredit": {
        "title": "JGSDF Type10 tank 20120527-16",
        "author": "Los688",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:JGSDF_Type10_tank_20120527-16.JPG",
        "license": "CC0",
        "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 11,
      "id": "ss",
      "phase": "Blending and doubled letters",
      "focus": "ss says s",
      "focusWords": [
        "miss",
        "kiss",
        "mess",
        "fuss",
        "hiss",
        "boss"
      ],
      "focusWordIds": [
        "word:miss",
        "word:kiss",
        "word:mess",
        "word:fuss",
        "word:hiss",
        "word:boss"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter S.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter S.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make one sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ss"
        },
        {
          "kind": "speech",
          "text": "miss. kiss."
        }
      ],
      "artwork": "images/word-course/tank-08-type-90.jpg",
      "artworkCredit": {
        "title": "Japanese Type 90 Tank - 1",
        "author": "Max Smith",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Japanese_Type_90_Tank_-_1.jpg",
        "license": "Public domain",
        "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 12,
      "id": "zz",
      "phase": "Blending and doubled letters",
      "focus": "zz says z",
      "focusWords": [
        "buzz",
        "fuzz",
        "fizz",
        "jazz"
      ],
      "focusWordIds": [
        "word:buzz",
        "word:fuzz",
        "word:fizz",
        "word:jazz"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter Z.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter Z.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make one sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "z"
        },
        {
          "kind": "speech",
          "text": "buzz. fuzz."
        }
      ],
      "artwork": "images/word-course/tank-09-ariete.jpg",
      "artworkCredit": {
        "title": "Ariete tank",
        "author": "Heinz Guderian",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Ariete_tank.JPG",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 13,
      "id": "sh",
      "phase": "Consonant teams",
      "focus": "sh, as in ship",
      "focusWords": [
        "ship",
        "shop",
        "shut",
        "shed",
        "fish",
        "wish"
      ],
      "focusWordIds": [
        "word:ship",
        "word:shop",
        "word:shut",
        "word:shed",
        "word:fish",
        "word:wish"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter S.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter H.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make one sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "sh"
        },
        {
          "kind": "speech",
          "text": "ship. shop."
        }
      ],
      "artwork": "images/l4_hammerchampion.jpg",
      "artworkCredit": null
    },
    {
      "level": 14,
      "id": "ch",
      "phase": "Consonant teams",
      "focus": "ch, as in chip",
      "focusWords": [
        "chip",
        "chop",
        "chin",
        "chat",
        "rich",
        "much"
      ],
      "focusWordIds": [
        "word:chip",
        "word:chop",
        "word:chin",
        "word:chat",
        "word:rich",
        "word:much"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter C.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter H.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make one sound. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ch"
        },
        {
          "kind": "speech",
          "text": "chip. chop."
        }
      ],
      "artwork": "images/word-course/tank-10-t-90.jpg",
      "artworkCredit": {
        "title": "Moscow 2012 Victory Day Parade Rehearsal, T-90 Tank, Russia",
        "author": "Vyacheslav Argenberg",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Moscow_2012_Victory_Day_Parade_Rehearsal,_T-90_Tank,_Russia.jpg",
        "license": "CC BY 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 15,
      "id": "unvoiced-th",
      "phase": "Consonant teams",
      "focus": "Quiet th, as in thin",
      "focusWords": [
        "thin",
        "thick",
        "thud",
        "moth",
        "cloth",
        "thrush"
      ],
      "focusWordIds": [
        "word:thin",
        "word:thick",
        "word:thud",
        "word:moth",
        "word:cloth",
        "word:thrush"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter T.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter H.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make the quiet sound at the start of thin. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "th"
        },
        {
          "kind": "speech",
          "text": "thin. thick."
        }
      ],
      "artwork": "images/word-course/tank-11-t-72.jpg",
      "artworkCredit": {
        "title": "A T-72 Main Battle Tank Prepares to Fire 15683",
        "author": "Sgt. 1st Class Brent Hunt",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:A_T-72_Main_Battle_Tank_Prepares_to_Fire_15683.jpg",
        "license": "Public domain",
        "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 16,
      "id": "voiced-th",
      "phase": "Consonant teams",
      "focus": "Buzzy th, as in this",
      "focusWords": [
        "this",
        "that",
        "them",
        "then",
        "than"
      ],
      "focusWordIds": [
        "word:this",
        "word:that",
        "word:them",
        "word:then",
        "word:than"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter T.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter H.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make the buzzy sound at the start of this. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "thv"
        },
        {
          "kind": "speech",
          "text": "this. that."
        }
      ],
      "artwork": "images/word-course/tank-12-t-80.jpg",
      "artworkCredit": {
        "title": "Soviet T-80 tank",
        "author": "Unknown author",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Soviet_T-80_tank.JPEG",
        "license": "Public domain",
        "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 17,
      "id": "ng",
      "phase": "Consonant teams",
      "focus": "ng, as in ring",
      "focusWords": [
        "bang",
        "hang",
        "rang",
        "ring",
        "sing",
        "king"
      ],
      "focusWordIds": [
        "word:bang",
        "word:hang",
        "word:rang",
        "word:ring",
        "word:sing",
        "word:king"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter N.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter G.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make the sound at the end of ring. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ng"
        },
        {
          "kind": "speech",
          "text": "bang. hang."
        }
      ],
      "artwork": "images/l5_scouts.jpg",
      "artworkCredit": null
    },
    {
      "level": 18,
      "id": "qu",
      "phase": "Consonant teams",
      "focus": "qu says kw",
      "focusWords": [
        "quit",
        "quiz",
        "quill",
        "quack",
        "quick",
        "quest"
      ],
      "focusWordIds": [
        "word:quit",
        "word:quiz",
        "word:quill",
        "word:quack",
        "word:quick",
        "word:quest"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter Q.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter U.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Together they make the sounds at the start of quit. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "qu"
        },
        {
          "kind": "speech",
          "text": "quit. quiz."
        }
      ],
      "artwork": "images/word-course/tank-13-t-64.jpg",
      "artworkCredit": {
        "title": "T-64 Lutsk",
        "author": "Bandanschik",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:T-64_Lutsk.jpg",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 19,
      "id": "a-e",
      "phase": "Silent final e",
      "focus": "a-e, as in cake",
      "focusWords": [
        "cake",
        "name",
        "game",
        "tape",
        "wave",
        "late"
      ],
      "focusWordIds": [
        "word:cake",
        "word:name",
        "word:game",
        "word:tape",
        "word:wave",
        "word:late"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter A.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, this vowel says its name."
        },
        {
          "kind": "speech",
          "text": "Letter E.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "The letter at the end is silent. Listen to the vowel sound."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ay"
        },
        {
          "kind": "speech",
          "text": "cake. name."
        }
      ],
      "artwork": "images/word-course/tank-14-chieftain.jpg",
      "artworkCredit": {
        "title": "Chieftain lesany",
        "author": "Adamicz",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Chieftain_lesany.jpg",
        "license": "CC BY-SA 3.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 20,
      "id": "i-e",
      "phase": "Silent final e",
      "focus": "i-e, as in bike",
      "focusWords": [
        "bike",
        "kite",
        "time",
        "five",
        "lime",
        "hide"
      ],
      "focusWordIds": [
        "word:bike",
        "word:kite",
        "word:time",
        "word:five",
        "word:lime",
        "word:hide"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter I.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, this vowel says its name."
        },
        {
          "kind": "speech",
          "text": "Letter E.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "The letter at the end is silent. Listen to the vowel sound."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "igh"
        },
        {
          "kind": "speech",
          "text": "bike. kite."
        }
      ],
      "artwork": "images/word-course/tank-15-centurion.jpg",
      "artworkCredit": {
        "title": "Centurion in the Bovington Tank Museum at the Tank Museum, Bovington 02",
        "author": "Mightyhansa",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Centurion_in_the_Bovington_Tank_Museum_at_the_Tank_Museum,_Bovington_02.jpg",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 21,
      "id": "o-e",
      "phase": "Silent final e",
      "focus": "o-e, as in home",
      "focusWords": [
        "home",
        "hope",
        "rope",
        "bone",
        "cone",
        "note"
      ],
      "focusWordIds": [
        "word:home",
        "word:hope",
        "word:rope",
        "word:bone",
        "word:cone",
        "word:note"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, this vowel says its name."
        },
        {
          "kind": "speech",
          "text": "Letter E.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "The letter at the end is silent. Listen to the vowel sound."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "oa"
        },
        {
          "kind": "speech",
          "text": "home. hope."
        }
      ],
      "artwork": "images/l6_muster.jpg",
      "artworkCredit": null
    },
    {
      "level": 22,
      "id": "u-e-yoo",
      "phase": "Silent final e",
      "focus": "u-e says yoo",
      "focusWords": [
        "cube",
        "cute",
        "mule",
        "mute",
        "fume"
      ],
      "focusWordIds": [
        "word:cube",
        "word:cute",
        "word:mule",
        "word:mute",
        "word:fume"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter U.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, this vowel says its name."
        },
        {
          "kind": "speech",
          "text": "Letter E.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "The letter at the end is silent. Listen to the vowel sound."
        },
        {
          "kind": "speech",
          "text": "Its name sounds like the word you."
        },
        {
          "kind": "speech",
          "text": "You."
        },
        {
          "kind": "speech",
          "text": "cube. cute."
        }
      ],
      "artwork": "images/word-course/tank-16-m60.jpg",
      "artworkCredit": {
        "title": "M60 Tank veterans memorial",
        "author": "Godstar23",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:M60_Tank_veterans_memorial.jpg",
        "license": "CC0",
        "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 23,
      "id": "ee",
      "phase": "Vowel teams",
      "focus": "ee, as in feet",
      "focusWords": [
        "bee",
        "see",
        "feet",
        "seed",
        "sheep",
        "green"
      ],
      "focusWordIds": [
        "word:bee",
        "word:see",
        "word:feet",
        "word:seed",
        "word:sheep",
        "word:green"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter E.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter E.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ee"
        },
        {
          "kind": "speech",
          "text": "bee. see."
        }
      ],
      "artwork": "images/word-course/tank-17-m48-patton.jpg",
      "artworkCredit": {
        "title": "M48 Patton Tank at Fort Sam Houston Museum",
        "author": "Articseahorse",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:M48_Patton_Tank_at_Fort_Sam_Houston_Museum.jpg",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 24,
      "id": "ai",
      "phase": "Vowel teams",
      "focus": "ai, as in rain",
      "focusWords": [
        "rain",
        "pain",
        "tail",
        "sail",
        "mail",
        "train"
      ],
      "focusWordIds": [
        "word:rain",
        "word:pain",
        "word:tail",
        "word:sail",
        "word:mail",
        "word:train"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter A.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter I.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ay"
        },
        {
          "kind": "speech",
          "text": "rain. pain."
        }
      ],
      "artwork": "images/word-course/tank-18-m26-pershing.jpg",
      "artworkCredit": {
        "title": "M26 Pershing at the Texas Military Forces Museum",
        "author": "Articseahorse",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:M26_Pershing_at_the_Texas_Military_Forces_Museum.jpg",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 25,
      "id": "ay",
      "phase": "Vowel teams",
      "focus": "ay, as in day",
      "focusWords": [
        "day",
        "pay",
        "say",
        "way",
        "ray",
        "play"
      ],
      "focusWordIds": [
        "word:day",
        "word:pay",
        "word:say",
        "word:way",
        "word:ray",
        "word:play"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter A.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter Y.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ay"
        },
        {
          "kind": "speech",
          "text": "day. pay."
        }
      ],
      "artwork": "images/l7_saint.jpg",
      "artworkCredit": null
    },
    {
      "level": 26,
      "id": "oa",
      "phase": "Vowel teams",
      "focus": "oa, as in boat",
      "focusWords": [
        "boat",
        "coat",
        "goat",
        "road",
        "soap",
        "toad"
      ],
      "focusWordIds": [
        "word:boat",
        "word:coat",
        "word:goat",
        "word:road",
        "word:soap",
        "word:toad"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter A.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "oa"
        },
        {
          "kind": "speech",
          "text": "boat. coat."
        }
      ],
      "artwork": "images/word-course/tank-19-sherman.jpg",
      "artworkCredit": {
        "title": "M4 Sherman tank - Flickr - Joost J. Bakker IJmuiden",
        "author": "Joost J. Bakker",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:M4_Sherman_tank_-_Flickr_-_Joost_J._Bakker_IJmuiden.jpg",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 27,
      "id": "long-oo",
      "phase": "Vowel teams",
      "focus": "oo, as in moon",
      "focusWords": [
        "moon",
        "food",
        "soon",
        "boot",
        "pool",
        "spoon"
      ],
      "focusWordIds": [
        "word:moon",
        "word:food",
        "word:soon",
        "word:boot",
        "word:pool",
        "word:spoon"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters make the vowel sound in moon. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "oo"
        },
        {
          "kind": "speech",
          "text": "moon. food."
        }
      ],
      "artwork": "images/word-course/tank-20-churchill.jpg",
      "artworkCredit": {
        "title": "Tanks and Afvs of the British Army 1939-45 KID1265",
        "author": "Unknown author",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Tanks_and_Afvs_of_the_British_Army_1939-45_KID1265.jpg",
        "license": "Public domain",
        "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 28,
      "id": "short-oo",
      "phase": "Vowel teams",
      "focus": "oo, as in book",
      "focusWords": [
        "book",
        "cook",
        "look",
        "took",
        "foot",
        "good"
      ],
      "focusWordIds": [
        "word:book",
        "word:cook",
        "word:look",
        "word:took",
        "word:foot",
        "word:good"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters make the vowel sound in book. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ooshort"
        },
        {
          "kind": "speech",
          "text": "book. cook."
        }
      ],
      "artwork": "images/word-course/tank-21-cromwell.jpg",
      "artworkCredit": {
        "title": "Cromwell Tank (13538144563)",
        "author": "FaceMePLS from The Hague, The Netherlands",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Cromwell_Tank_(13538144563).jpg",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 29,
      "id": "igh",
      "phase": "Vowel teams",
      "focus": "igh, as in night",
      "focusWords": [
        "high",
        "sigh",
        "night",
        "light",
        "right",
        "tight"
      ],
      "focusWordIds": [
        "word:high",
        "word:sigh",
        "word:night",
        "word:light",
        "word:right",
        "word:tight"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter I.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter G.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter H.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "igh"
        },
        {
          "kind": "speech",
          "text": "high. sigh."
        }
      ],
      "artwork": "images/l8_battleship.jpg",
      "artworkCredit": null
    },
    {
      "level": 30,
      "id": "ow-cow",
      "phase": "More vowel teams",
      "focus": "ow, as in cow",
      "focusWords": [
        "cow",
        "how",
        "now",
        "down",
        "town",
        "brown"
      ],
      "focusWordIds": [
        "word:cow",
        "word:how",
        "word:now",
        "word:down",
        "word:town",
        "word:brown"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter W.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters make the vowel sound in cow. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ow"
        },
        {
          "kind": "speech",
          "text": "cow. how."
        }
      ],
      "artwork": "images/word-course/tank-22-comet.jpg",
      "artworkCredit": {
        "title": "Comet I - Tank Museum Bovington 19-05-2017 10-58-09",
        "author": "Paul Hermans",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Comet_I_-_Tank_Museum_Bovington_19-05-2017_10-58-09.jpg",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 31,
      "id": "ou",
      "phase": "More vowel teams",
      "focus": "ou, as in out",
      "focusWords": [
        "out",
        "shout",
        "cloud",
        "loud",
        "proud",
        "round"
      ],
      "focusWordIds": [
        "word:out",
        "word:shout",
        "word:cloud",
        "word:loud",
        "word:proud",
        "word:round"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter U.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters make the vowel sound in out. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ow"
        },
        {
          "kind": "speech",
          "text": "out. shout."
        }
      ],
      "artwork": "images/word-course/tank-23-valentine.jpg",
      "artworkCredit": {
        "title": "Bovington Tank Museum, Valentine II, Mk 3 tank - geograph.org.uk - 6647199",
        "author": "Michael Garlick",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Bovington_Tank_Museum,_Valentine_II,_Mk_3_tank_-_geograph.org.uk_-_6647199.jpg",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 32,
      "id": "ow-snow",
      "phase": "More vowel teams",
      "focus": "ow, as in snow",
      "focusWords": [
        "low",
        "slow",
        "snow",
        "grow",
        "blow",
        "flow"
      ],
      "focusWordIds": [
        "word:low",
        "word:slow",
        "word:snow",
        "word:grow",
        "word:blow",
        "word:flow"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter W.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters make the vowel sound in snow. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "oa"
        },
        {
          "kind": "speech",
          "text": "low. slow."
        }
      ],
      "artwork": "images/word-course/tank-24-crusader.jpg",
      "artworkCredit": {
        "title": "Crusader tanks in Yorkshire 1942",
        "author": "War Office official photographer",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Crusader_tanks_in_Yorkshire_1942.jpg",
        "license": "Public domain",
        "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Copyright_tags#Public_domain",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 33,
      "id": "oi",
      "phase": "More vowel teams",
      "focus": "oi, as in coin",
      "focusWords": [
        "oil",
        "boil",
        "coil",
        "foil",
        "coin",
        "join"
      ],
      "focusWordIds": [
        "word:oil",
        "word:boil",
        "word:coil",
        "word:foil",
        "word:coin",
        "word:join"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter I.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "oi"
        },
        {
          "kind": "speech",
          "text": "oil. boil."
        }
      ],
      "artwork": "images/word-course/tank-25-matilda.jpg",
      "artworkCredit": {
        "title": "The Matilda Tank (geograph 3416319)",
        "author": "Bill Nicholls",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:The_Matilda_Tank_(geograph_3416319).jpg",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 34,
      "id": "oy",
      "phase": "More vowel teams",
      "focus": "oy, as in toy",
      "focusWords": [
        "boy",
        "toy",
        "joy",
        "soy"
      ],
      "focusWordIds": [
        "word:boy",
        "word:toy",
        "word:joy",
        "word:soy"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter Y.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "oy"
        },
        {
          "kind": "speech",
          "text": "boy. toy."
        }
      ],
      "artwork": "images/word-course/tank-26-panther.jpg",
      "artworkCredit": {
        "title": "Panther Tank - geograph.org.uk - 3416162",
        "author": "Bill Nicholls",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Panther_Tank_-_geograph.org.uk_-_3416162.jpg",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 35,
      "id": "ar",
      "phase": "Vowels with r",
      "focus": "ar, as in car",
      "focusWords": [
        "car",
        "far",
        "jar",
        "arm",
        "farm",
        "star"
      ],
      "focusWordIds": [
        "word:car",
        "word:far",
        "word:jar",
        "word:arm",
        "word:farm",
        "word:star"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter A.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter R.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ar"
        },
        {
          "kind": "speech",
          "text": "car. far."
        }
      ],
      "artwork": "images/l9_titanparade.jpg",
      "artworkCredit": null
    },
    {
      "level": 36,
      "id": "or",
      "phase": "Vowels with r",
      "focus": "or, as in fork",
      "focusWords": [
        "fork",
        "corn",
        "cord",
        "horn",
        "short",
        "sport"
      ],
      "focusWordIds": [
        "word:fork",
        "word:corn",
        "word:cord",
        "word:horn",
        "word:short",
        "word:sport"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter O.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter R.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "or"
        },
        {
          "kind": "speech",
          "text": "fork. corn."
        }
      ],
      "artwork": "images/word-course/tank-27-tiger.jpg",
      "artworkCredit": {
        "title": "Tiger Tank - geograph.org.uk - 3388143",
        "author": "Peter Trimming",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Tiger_Tank_-_geograph.org.uk_-_3388143.jpg",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 37,
      "id": "ur",
      "phase": "Vowels with r",
      "focus": "ur, as in turn",
      "focusWords": [
        "fur",
        "burn",
        "turn",
        "hurt",
        "curl",
        "surf"
      ],
      "focusWordIds": [
        "word:fur",
        "word:burn",
        "word:turn",
        "word:hurt",
        "word:curl",
        "word:surf"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter U.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter R.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "er"
        },
        {
          "kind": "speech",
          "text": "fur. burn."
        }
      ],
      "artwork": "images/word-course/tank-28-panzer-iv.jpg",
      "artworkCredit": {
        "title": "Bovington Tank Museum, Panzer IV 'Ausf D' tank - geograph.org.uk - 6647232",
        "author": "Michael Garlick",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Bovington_Tank_Museum,_Panzer_IV_%27Ausf_D%27_tank_-_geograph.org.uk_-_6647232.jpg",
        "license": "CC BY-SA 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 38,
      "id": "er",
      "phase": "Vowels with r",
      "focus": "er, as in fern",
      "focusWords": [
        "fern",
        "herd",
        "term",
        "verb",
        "perch",
        "stern"
      ],
      "focusWordIds": [
        "word:fern",
        "word:herd",
        "word:term",
        "word:verb",
        "word:perch",
        "word:stern"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter E.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter R.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "er"
        },
        {
          "kind": "speech",
          "text": "fern. herd."
        }
      ],
      "artwork": "images/word-course/tank-29-t-34.jpg",
      "artworkCredit": {
        "title": "Tank T-34",
        "author": "Cezary Piwowarski",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Tank_T-34.JPG",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 39,
      "id": "ir",
      "phase": "Vowels with r",
      "focus": "ir, as in bird",
      "focusWords": [
        "bird",
        "girl",
        "dirt",
        "firm",
        "stir",
        "third"
      ],
      "focusWordIds": [
        "word:bird",
        "word:girl",
        "word:dirt",
        "word:firm",
        "word:stir",
        "word:third"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter I.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter R.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "ir"
        },
        {
          "kind": "speech",
          "text": "bird. girl."
        }
      ],
      "artwork": "images/word-course/tank-30-kv-1.jpg",
      "artworkCredit": {
        "title": "Parola Tank Museum 089 - KV-1 (38513872506)",
        "author": "Richard Allen from Nottingham, UK",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Parola_Tank_Museum_089_-_KV-1_(38513872506).jpg",
        "license": "CC BY 2.0",
        "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 40,
      "id": "aw",
      "phase": "aw spellings",
      "focus": "aw, as in saw",
      "focusWords": [
        "saw",
        "paw",
        "jaw",
        "raw",
        "claw",
        "draw"
      ],
      "focusWordIds": [
        "word:saw",
        "word:paw",
        "word:jaw",
        "word:raw",
        "word:claw",
        "word:draw"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter A.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter W.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, these letters work together. Listen."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "aw"
        },
        {
          "kind": "speech",
          "text": "saw. paw."
        }
      ],
      "artwork": "images/word-course/tank-31-renault-ft.jpg",
      "artworkCredit": {
        "title": "Renault FT-17 (1)",
        "author": "Reise Reise",
        "sourcePageUrl": "https://commons.wikimedia.org/wiki/File:Renault_FT-17_(1).jpg",
        "license": "CC BY-SA 4.0",
        "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
        "modifications": "Resized to a maximum width of 1600 pixels and re-encoded as JPEG; no other changes."
      }
    },
    {
      "level": 41,
      "id": "a-before-ll",
      "phase": "aw spellings",
      "focus": "a before ll, as in ball",
      "focusWords": [
        "all",
        "ball",
        "call",
        "fall",
        "hall",
        "tall"
      ],
      "focusWordIds": [
        "word:all",
        "word:ball",
        "word:call",
        "word:fall",
        "word:hall",
        "word:tall"
      ],
      "rulePlaybackSteps": [
        {
          "kind": "speech",
          "text": "Letter A.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "In these words, this vowel comes before two of the next letter."
        },
        {
          "kind": "speech",
          "text": "Letter L.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Letter L.",
          "rate": 0.72,
          "pauseAfterMs": 220
        },
        {
          "kind": "speech",
          "text": "Listen to the vowel sound in ball."
        },
        {
          "kind": "recorded-sound",
          "clipKey": "aw"
        },
        {
          "kind": "speech",
          "text": "all. ball."
        }
      ],
      "artwork": "images/l10_ringplanet.jpg",
      "artworkCredit": null
    }
  ],
  "startingWordIds": [
    "word:mat",
    "word:dad",
    "word:hat"
  ],
  "additionalWords": [
    {
      "id": "word:jam",
      "display": "jam",
      "accepted": [
        "jam"
      ],
      "level": 1
    },
    {
      "id": "word:red",
      "display": "red",
      "accepted": [
        "red"
      ],
      "level": 2
    },
    {
      "id": "word:dig",
      "display": "dig",
      "accepted": [
        "dig"
      ],
      "level": 3
    },
    {
      "id": "word:top",
      "display": "top",
      "accepted": [
        "top"
      ],
      "level": 4
    },
    {
      "id": "word:hut",
      "display": "hut",
      "accepted": [
        "hut"
      ],
      "level": 5
    },
    {
      "id": "word:plum",
      "display": "plum",
      "accepted": [
        "plum"
      ],
      "level": 6
    },
    {
      "id": "word:stop",
      "display": "stop",
      "accepted": [
        "stop"
      ],
      "level": 6
    },
    {
      "id": "word:swim",
      "display": "swim",
      "accepted": [
        "swim"
      ],
      "level": 6
    },
    {
      "id": "word:hand",
      "display": "hand",
      "accepted": [
        "hand"
      ],
      "level": 7
    },
    {
      "id": "word:tent",
      "display": "tent",
      "accepted": [
        "tent"
      ],
      "level": 7
    },
    {
      "id": "word:lamp",
      "display": "lamp",
      "accepted": [
        "lamp"
      ],
      "level": 7
    },
    {
      "id": "word:pond",
      "display": "pond",
      "accepted": [
        "pond"
      ],
      "level": 7
    },
    {
      "id": "word:dust",
      "display": "dust",
      "accepted": [
        "dust"
      ],
      "level": 7
    },
    {
      "id": "word:neck",
      "display": "neck",
      "accepted": [
        "neck"
      ],
      "level": 8
    },
    {
      "id": "word:kick",
      "display": "kick",
      "accepted": [
        "kick"
      ],
      "level": 8
    },
    {
      "id": "word:puff",
      "display": "puff",
      "accepted": [
        "puff"
      ],
      "level": 9
    },
    {
      "id": "word:huff",
      "display": "huff",
      "accepted": [
        "huff"
      ],
      "level": 9
    },
    {
      "id": "word:cuff",
      "display": "cuff",
      "accepted": [
        "cuff"
      ],
      "level": 9
    },
    {
      "id": "word:sniff",
      "display": "sniff",
      "accepted": [
        "sniff"
      ],
      "level": 9
    },
    {
      "id": "word:stiff",
      "display": "stiff",
      "accepted": [
        "stiff"
      ],
      "level": 9
    },
    {
      "id": "word:bell",
      "display": "bell",
      "accepted": [
        "bell"
      ],
      "level": 10
    },
    {
      "id": "word:hill",
      "display": "hill",
      "accepted": [
        "hill"
      ],
      "level": 10
    },
    {
      "id": "word:doll",
      "display": "doll",
      "accepted": [
        "doll"
      ],
      "level": 10
    },
    {
      "id": "word:well",
      "display": "well",
      "accepted": [
        "well"
      ],
      "level": 10
    },
    {
      "id": "word:fill",
      "display": "fill",
      "accepted": [
        "fill"
      ],
      "level": 10
    },
    {
      "id": "word:miss",
      "display": "miss",
      "accepted": [
        "miss"
      ],
      "level": 11
    },
    {
      "id": "word:kiss",
      "display": "kiss",
      "accepted": [
        "kiss"
      ],
      "level": 11
    },
    {
      "id": "word:mess",
      "display": "mess",
      "accepted": [
        "mess"
      ],
      "level": 11
    },
    {
      "id": "word:fuss",
      "display": "fuss",
      "accepted": [
        "fuss"
      ],
      "level": 11
    },
    {
      "id": "word:hiss",
      "display": "hiss",
      "accepted": [
        "hiss"
      ],
      "level": 11
    },
    {
      "id": "word:boss",
      "display": "boss",
      "accepted": [
        "boss"
      ],
      "level": 11
    },
    {
      "id": "word:buzz",
      "display": "buzz",
      "accepted": [
        "buzz"
      ],
      "level": 12
    },
    {
      "id": "word:fuzz",
      "display": "fuzz",
      "accepted": [
        "fuzz"
      ],
      "level": 12
    },
    {
      "id": "word:fizz",
      "display": "fizz",
      "accepted": [
        "fizz"
      ],
      "level": 12
    },
    {
      "id": "word:jazz",
      "display": "jazz",
      "accepted": [
        "jazz"
      ],
      "level": 12
    },
    {
      "id": "word:shop",
      "display": "shop",
      "accepted": [
        "shop"
      ],
      "level": 13
    },
    {
      "id": "word:shut",
      "display": "shut",
      "accepted": [
        "shut"
      ],
      "level": 13
    },
    {
      "id": "word:shed",
      "display": "shed",
      "accepted": [
        "shed"
      ],
      "level": 13
    },
    {
      "id": "word:chop",
      "display": "chop",
      "accepted": [
        "chop"
      ],
      "level": 14
    },
    {
      "id": "word:chin",
      "display": "chin",
      "accepted": [
        "chin"
      ],
      "level": 14
    },
    {
      "id": "word:chat",
      "display": "chat",
      "accepted": [
        "chat"
      ],
      "level": 14
    },
    {
      "id": "word:rich",
      "display": "rich",
      "accepted": [
        "rich"
      ],
      "level": 14
    },
    {
      "id": "word:thick",
      "display": "thick",
      "accepted": [
        "thick"
      ],
      "level": 15
    },
    {
      "id": "word:thud",
      "display": "thud",
      "accepted": [
        "thud"
      ],
      "level": 15
    },
    {
      "id": "word:moth",
      "display": "moth",
      "accepted": [
        "moth"
      ],
      "level": 15
    },
    {
      "id": "word:cloth",
      "display": "cloth",
      "accepted": [
        "cloth"
      ],
      "level": 15
    },
    {
      "id": "word:thrush",
      "display": "thrush",
      "accepted": [
        "thrush"
      ],
      "level": 15
    },
    {
      "id": "word:this",
      "display": "this",
      "accepted": [
        "this"
      ],
      "level": 16
    },
    {
      "id": "word:that",
      "display": "that",
      "accepted": [
        "that"
      ],
      "level": 16
    },
    {
      "id": "word:them",
      "display": "them",
      "accepted": [
        "them"
      ],
      "level": 16
    },
    {
      "id": "word:then",
      "display": "then",
      "accepted": [
        "then"
      ],
      "level": 16
    },
    {
      "id": "word:than",
      "display": "than",
      "accepted": [
        "than"
      ],
      "level": 16
    },
    {
      "id": "word:bang",
      "display": "bang",
      "accepted": [
        "bang"
      ],
      "level": 17
    },
    {
      "id": "word:hang",
      "display": "hang",
      "accepted": [
        "hang"
      ],
      "level": 17
    },
    {
      "id": "word:rang",
      "display": "rang",
      "accepted": [
        "rang"
      ],
      "level": 17
    },
    {
      "id": "word:ring",
      "display": "ring",
      "accepted": [
        "ring"
      ],
      "level": 17
    },
    {
      "id": "word:king",
      "display": "king",
      "accepted": [
        "king"
      ],
      "level": 17
    },
    {
      "id": "word:quit",
      "display": "quit",
      "accepted": [
        "quit"
      ],
      "level": 18
    },
    {
      "id": "word:quiz",
      "display": "quiz",
      "accepted": [
        "quiz"
      ],
      "level": 18
    },
    {
      "id": "word:quill",
      "display": "quill",
      "accepted": [
        "quill"
      ],
      "level": 18
    },
    {
      "id": "word:quack",
      "display": "quack",
      "accepted": [
        "quack"
      ],
      "level": 18
    },
    {
      "id": "word:quick",
      "display": "quick",
      "accepted": [
        "quick"
      ],
      "level": 18
    },
    {
      "id": "word:quest",
      "display": "quest",
      "accepted": [
        "quest"
      ],
      "level": 18
    },
    {
      "id": "word:game",
      "display": "game",
      "accepted": [
        "game"
      ],
      "level": 19
    },
    {
      "id": "word:wave",
      "display": "wave",
      "accepted": [
        "wave"
      ],
      "level": 19
    },
    {
      "id": "word:late",
      "display": "late",
      "accepted": [
        "late"
      ],
      "level": 19
    },
    {
      "id": "word:kite",
      "display": "kite",
      "accepted": [
        "kite"
      ],
      "level": 20
    },
    {
      "id": "word:lime",
      "display": "lime",
      "accepted": [
        "lime"
      ],
      "level": 20
    },
    {
      "id": "word:hide",
      "display": "hide",
      "accepted": [
        "hide"
      ],
      "level": 20
    },
    {
      "id": "word:hope",
      "display": "hope",
      "accepted": [
        "hope"
      ],
      "level": 21
    },
    {
      "id": "word:rope",
      "display": "rope",
      "accepted": [
        "rope"
      ],
      "level": 21
    },
    {
      "id": "word:cone",
      "display": "cone",
      "accepted": [
        "cone"
      ],
      "level": 21
    },
    {
      "id": "word:mule",
      "display": "mule",
      "accepted": [
        "mule"
      ],
      "level": 22
    },
    {
      "id": "word:mute",
      "display": "mute",
      "accepted": [
        "mute"
      ],
      "level": 22
    },
    {
      "id": "word:fume",
      "display": "fume",
      "accepted": [
        "fume"
      ],
      "level": 22
    },
    {
      "id": "word:bee",
      "display": "bee",
      "accepted": [
        "bee"
      ],
      "level": 23
    },
    {
      "id": "word:feet",
      "display": "feet",
      "accepted": [
        "feet"
      ],
      "level": 23
    },
    {
      "id": "word:seed",
      "display": "seed",
      "accepted": [
        "seed"
      ],
      "level": 23
    },
    {
      "id": "word:sheep",
      "display": "sheep",
      "accepted": [
        "sheep"
      ],
      "level": 23
    },
    {
      "id": "word:pain",
      "display": "pain",
      "accepted": [
        "pain"
      ],
      "level": 24
    },
    {
      "id": "word:tail",
      "display": "tail",
      "accepted": [
        "tail"
      ],
      "level": 24
    },
    {
      "id": "word:sail",
      "display": "sail",
      "accepted": [
        "sail"
      ],
      "level": 24
    },
    {
      "id": "word:mail",
      "display": "mail",
      "accepted": [
        "mail"
      ],
      "level": 24
    },
    {
      "id": "word:pay",
      "display": "pay",
      "accepted": [
        "pay"
      ],
      "level": 25
    },
    {
      "id": "word:ray",
      "display": "ray",
      "accepted": [
        "ray"
      ],
      "level": 25
    },
    {
      "id": "word:goat",
      "display": "goat",
      "accepted": [
        "goat"
      ],
      "level": 26
    },
    {
      "id": "word:soap",
      "display": "soap",
      "accepted": [
        "soap"
      ],
      "level": 26
    },
    {
      "id": "word:toad",
      "display": "toad",
      "accepted": [
        "toad"
      ],
      "level": 26
    },
    {
      "id": "word:soon",
      "display": "soon",
      "accepted": [
        "soon"
      ],
      "level": 27
    },
    {
      "id": "word:pool",
      "display": "pool",
      "accepted": [
        "pool"
      ],
      "level": 27
    },
    {
      "id": "word:spoon",
      "display": "spoon",
      "accepted": [
        "spoon"
      ],
      "level": 27
    },
    {
      "id": "word:cook",
      "display": "cook",
      "accepted": [
        "cook"
      ],
      "level": 28
    },
    {
      "id": "word:look",
      "display": "look",
      "accepted": [
        "look"
      ],
      "level": 28
    },
    {
      "id": "word:took",
      "display": "took",
      "accepted": [
        "took"
      ],
      "level": 28
    },
    {
      "id": "word:foot",
      "display": "foot",
      "accepted": [
        "foot"
      ],
      "level": 28
    },
    {
      "id": "word:good",
      "display": "good",
      "accepted": [
        "good"
      ],
      "level": 28
    },
    {
      "id": "word:sigh",
      "display": "sigh",
      "accepted": [
        "sigh"
      ],
      "level": 29
    },
    {
      "id": "word:tight",
      "display": "tight",
      "accepted": [
        "tight"
      ],
      "level": 29
    },
    {
      "id": "word:cow",
      "display": "cow",
      "accepted": [
        "cow"
      ],
      "level": 30
    },
    {
      "id": "word:how",
      "display": "how",
      "accepted": [
        "how"
      ],
      "level": 30
    },
    {
      "id": "word:now",
      "display": "now",
      "accepted": [
        "now"
      ],
      "level": 30
    },
    {
      "id": "word:town",
      "display": "town",
      "accepted": [
        "town"
      ],
      "level": 30
    },
    {
      "id": "word:brown",
      "display": "brown",
      "accepted": [
        "brown"
      ],
      "level": 30
    },
    {
      "id": "word:out",
      "display": "out",
      "accepted": [
        "out"
      ],
      "level": 31
    },
    {
      "id": "word:shout",
      "display": "shout",
      "accepted": [
        "shout"
      ],
      "level": 31
    },
    {
      "id": "word:cloud",
      "display": "cloud",
      "accepted": [
        "cloud"
      ],
      "level": 31
    },
    {
      "id": "word:loud",
      "display": "loud",
      "accepted": [
        "loud"
      ],
      "level": 31
    },
    {
      "id": "word:proud",
      "display": "proud",
      "accepted": [
        "proud"
      ],
      "level": 31
    },
    {
      "id": "word:round",
      "display": "round",
      "accepted": [
        "round"
      ],
      "level": 31
    },
    {
      "id": "word:low",
      "display": "low",
      "accepted": [
        "low"
      ],
      "level": 32
    },
    {
      "id": "word:slow",
      "display": "slow",
      "accepted": [
        "slow"
      ],
      "level": 32
    },
    {
      "id": "word:snow",
      "display": "snow",
      "accepted": [
        "snow"
      ],
      "level": 32
    },
    {
      "id": "word:blow",
      "display": "blow",
      "accepted": [
        "blow"
      ],
      "level": 32
    },
    {
      "id": "word:flow",
      "display": "flow",
      "accepted": [
        "flow"
      ],
      "level": 32
    },
    {
      "id": "word:oil",
      "display": "oil",
      "accepted": [
        "oil"
      ],
      "level": 33
    },
    {
      "id": "word:boil",
      "display": "boil",
      "accepted": [
        "boil"
      ],
      "level": 33
    },
    {
      "id": "word:coil",
      "display": "coil",
      "accepted": [
        "coil"
      ],
      "level": 33
    },
    {
      "id": "word:foil",
      "display": "foil",
      "accepted": [
        "foil"
      ],
      "level": 33
    },
    {
      "id": "word:joy",
      "display": "joy",
      "accepted": [
        "joy"
      ],
      "level": 34
    },
    {
      "id": "word:soy",
      "display": "soy",
      "accepted": [
        "soy"
      ],
      "level": 34
    },
    {
      "id": "word:jar",
      "display": "jar",
      "accepted": [
        "jar"
      ],
      "level": 35
    },
    {
      "id": "word:cord",
      "display": "cord",
      "accepted": [
        "cord"
      ],
      "level": 36
    },
    {
      "id": "word:sport",
      "display": "sport",
      "accepted": [
        "sport"
      ],
      "level": 36
    },
    {
      "id": "word:fur",
      "display": "fur",
      "accepted": [
        "fur"
      ],
      "level": 37
    },
    {
      "id": "word:curl",
      "display": "curl",
      "accepted": [
        "curl"
      ],
      "level": 37
    },
    {
      "id": "word:surf",
      "display": "surf",
      "accepted": [
        "surf"
      ],
      "level": 37
    },
    {
      "id": "word:fern",
      "display": "fern",
      "accepted": [
        "fern"
      ],
      "level": 38
    },
    {
      "id": "word:herd",
      "display": "herd",
      "accepted": [
        "herd"
      ],
      "level": 38
    },
    {
      "id": "word:term",
      "display": "term",
      "accepted": [
        "term"
      ],
      "level": 38
    },
    {
      "id": "word:verb",
      "display": "verb",
      "accepted": [
        "verb"
      ],
      "level": 38
    },
    {
      "id": "word:perch",
      "display": "perch",
      "accepted": [
        "perch"
      ],
      "level": 38
    },
    {
      "id": "word:stern",
      "display": "stern",
      "accepted": [
        "stern"
      ],
      "level": 38
    },
    {
      "id": "word:dirt",
      "display": "dirt",
      "accepted": [
        "dirt"
      ],
      "level": 39
    },
    {
      "id": "word:firm",
      "display": "firm",
      "accepted": [
        "firm"
      ],
      "level": 39
    },
    {
      "id": "word:stir",
      "display": "stir",
      "accepted": [
        "stir"
      ],
      "level": 39
    },
    {
      "id": "word:third",
      "display": "third",
      "accepted": [
        "third"
      ],
      "level": 39
    },
    {
      "id": "word:saw",
      "display": "saw",
      "accepted": [
        "saw"
      ],
      "level": 40
    },
    {
      "id": "word:paw",
      "display": "paw",
      "accepted": [
        "paw"
      ],
      "level": 40
    },
    {
      "id": "word:jaw",
      "display": "jaw",
      "accepted": [
        "jaw"
      ],
      "level": 40
    },
    {
      "id": "word:raw",
      "display": "raw",
      "accepted": [
        "raw"
      ],
      "level": 40
    },
    {
      "id": "word:claw",
      "display": "claw",
      "accepted": [
        "claw"
      ],
      "level": 40
    },
    {
      "id": "word:all",
      "display": "all",
      "accepted": [
        "all"
      ],
      "level": 41
    },
    {
      "id": "word:ball",
      "display": "ball",
      "accepted": [
        "ball"
      ],
      "level": 41
    },
    {
      "id": "word:hall",
      "display": "hall",
      "accepted": [
        "hall"
      ],
      "level": 41
    },
    {
      "id": "word:tall",
      "display": "tall",
      "accepted": [
        "tall"
      ],
      "level": 41
    }
  ],
  "roundRecipe": {
    "openingCount": 3,
    "focusCount": 4,
    "closingCount": 3
  }
};
